# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

jobs:
  tests:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - checkout
      - run: pip install --user -r requirements/testing.txt
      - run: tox -e py3
      - run: tox -e coverage

  checks:
    docker:
      - image: 'cimg/python:3.8'
    steps:
      - checkout
      - run: pip install --user -r requirements/testing.txt
      - run: tox -e migrations
      - run: tox -e lint
      - run: tox -e docs

workflows:
  version: 2
  test:
    jobs:
      - checks
      - tests
